version: 0.0
os: linux

files:
  - source: /
    destination: /data/test-app/frontend/dist/frontend

hooks:
  AfterInstall:
    - location: scripts/restart_nginx.sh
      timeout: 60
      runas: ubuntu

